import type { Announcement } from "@/lib/types";

export const announcements: Announcement[] = [
  {
    id: "ann-1",
    title: "New cohort applications now open",
    body: "SKAFF ACADEMY is now accepting applications across all technology, creative production, digital business, and professional development programs. Apply online or visit the campus admissions desk.",
    category: "admissions",
    audience: "all",
    publishedAt: "2025-12-10",
    authorStaffId: "staff-1",
    pinned: true,
  },
  {
    id: "ann-2",
    title: "Campus closed for public holiday",
    body: "The campus will be closed on the upcoming public holiday. Classes resume the following business day on the normal schedule.",
    category: "campus",
    audience: "all",
    publishedAt: "2025-12-01",
    authorStaffId: "staff-1",
  },
  {
    id: "ann-3",
    title: "Extended lab hours for project weeks",
    body: "Technology labs will remain open until 8pm on weekdays during project weeks to support hands-on coursework.",
    category: "academic",
    audience: "students",
    publishedAt: "2025-11-22",
    authorStaffId: "staff-2",
  },
  {
    id: "ann-4",
    title: "Audio and video studios open for practical sessions",
    body: "The audio production and video production studios are now available for scheduled practical sessions outside regular class hours.",
    category: "programs",
    audience: "students",
    publishedAt: "2025-11-15",
    authorStaffId: "staff-2",
  },
  {
    id: "ann-5",
    title: "React module materials now available",
    body: "Slides and reference links for the React module have been published. Check the Materials page for the full set, and join the optional project clinic if you'd like extra support.",
    category: "academic",
    audience: "students",
    programId: "prog-fullstack",
    publishedAt: "2025-12-14",
    authorStaffId: "staff-1",
  },
];
