import type { Assignment, Submission } from "@/lib/types";
import { relativeDay } from "./date-helpers";

export const assignments: Assignment[] = [
  {
    id: "asg-1",
    moduleId: "mod-1",
    classGroupId: "class-1",
    title: "Portfolio Landing Page",
    description: "Build a single-page personal portfolio using semantic HTML and CSS layout.",
    status: "closed",
    dueAt: relativeDay(-17, 23, 59),
    maxScore: 100,
    createdByStaffId: "staff-1",
  },
  {
    id: "asg-2",
    moduleId: "mod-2",
    classGroupId: "class-1",
    title: "JavaScript Fundamentals Homework",
    description: "Complete the practice exercises covering variables, functions, and arrays.",
    status: "closed",
    dueAt: relativeDay(-9, 23, 59),
    maxScore: 100,
    createdByStaffId: "staff-1",
  },
  {
    id: "asg-3",
    moduleId: "mod-3",
    classGroupId: "class-1",
    title: "React Component Library",
    description: "Build a small reusable component library (Button, Card, Badge) with React.",
    status: "published",
    dueAt: relativeDay(3, 23, 59),
    maxScore: 100,
    createdByStaffId: "staff-1",
  },
  {
    id: "asg-4",
    moduleId: "mod-3",
    classGroupId: "class-1",
    title: "React Mini App — Todo List",
    description: "Build a small todo list app using React state and component composition.",
    status: "published",
    dueAt: relativeDay(12, 23, 59),
    maxScore: 100,
    createdByStaffId: "staff-1",
  },
];

export const submissions: Submission[] = [
  {
    id: "sub-1",
    assignmentId: "asg-1",
    studentId: "student-1",
    status: "graded",
    fileName: "portfolio-landing-page.zip",
    fileType: "application/zip",
    fileSizeKb: 640,
    submittedAt: relativeDay(-18, 20),
    score: 88,
    feedback: "Clean structure and great use of semantic HTML. Watch your heading hierarchy.",
    gradedByStaffId: "staff-1",
  },
  {
    id: "sub-2",
    assignmentId: "asg-2",
    studentId: "student-1",
    status: "late",
    fileName: "js-fundamentals-homework.js",
    fileType: "text/javascript",
    fileSizeKb: 18,
    submittedAt: relativeDay(-8, 10),
    score: 74,
    feedback: "Good logic overall, but a couple of edge cases weren't handled. Submitted a day late.",
    gradedByStaffId: "staff-1",
  },
  {
    id: "sub-3",
    assignmentId: "asg-3",
    studentId: "student-1",
    status: "not_submitted",
  },
  {
    id: "sub-4",
    assignmentId: "asg-4",
    studentId: "student-1",
    status: "not_submitted",
  },
];
