import type { LearningMaterial } from "@/lib/types";
import { relativeDay } from "./date-helpers";

export const learningMaterials: LearningMaterial[] = [
  {
    id: "mat-1",
    moduleId: "mod-1",
    title: "Semantic HTML Cheat Sheet",
    description: "Reference sheet covering the semantic HTML elements used in class.",
    type: "document",
    fileUrl: "/mock-files/semantic-html-cheatsheet.pdf",
    fileSizeKb: 420,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-22, 8),
  },
  {
    id: "mat-2",
    moduleId: "mod-1",
    title: "CSS Layout Slides",
    description: "Lecture slides covering Flexbox, Grid, and responsive layout techniques.",
    type: "slide_deck",
    fileUrl: "/mock-files/css-layout-slides.pptx",
    fileSizeKb: 3150,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-19, 8),
  },
  {
    id: "mat-3",
    moduleId: "mod-1",
    title: "MDN: CSS Flexbox Guide",
    description: "Official reference documentation for CSS Flexbox.",
    type: "link",
    externalUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout",
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-19, 8),
  },
  {
    id: "mat-4",
    moduleId: "mod-2",
    title: "JavaScript Fundamentals Notes",
    description: "Full lecture notes for variables, functions, and control flow.",
    type: "document",
    fileUrl: "/mock-files/javascript-fundamentals-notes.pdf",
    fileSizeKb: 680,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-15, 8),
  },
  {
    id: "mat-5",
    moduleId: "mod-2",
    title: "DOM Manipulation Starter Files",
    description: "Starter project used during the DOM manipulation practical session.",
    type: "document",
    fileUrl: "/mock-files/dom-starter-files.zip",
    fileSizeKb: 128,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-11, 8),
  },
  {
    id: "mat-6",
    moduleId: "mod-3",
    title: "React Official Documentation",
    description: "Official React documentation — start with \"Describing the UI\".",
    type: "link",
    externalUrl: "https://react.dev/learn",
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-3, 8),
  },
  {
    id: "mat-7",
    moduleId: "mod-3",
    title: "Component Composition Slides",
    description: "Lecture slides on props, state, and composing React components.",
    type: "slide_deck",
    fileUrl: "/mock-files/react-composition-slides.pptx",
    fileSizeKb: 2740,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-2, 14),
  },
  {
    id: "mat-8",
    moduleId: "mod-3",
    title: "React Project Clinic Recording",
    description: "Recording of last term's project clinic session, still useful for reference.",
    type: "video",
    fileUrl: "/mock-files/react-clinic-recording.mp4",
    fileSizeKb: 184000,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-1, 10),
  },
  {
    id: "mat-9",
    moduleId: "mod-4",
    title: "Node.js & Express Setup Guide",
    description: "Step-by-step guide to setting up a Node.js and Express project.",
    type: "document",
    fileUrl: "/mock-files/nodejs-express-setup.pdf",
    fileSizeKb: 510,
    uploadedByStaffId: "staff-1",
    uploadedAt: relativeDay(-1, 9),
  },
];
