import type { Program, Intake, ClassGroup } from "@/lib/types";
import { relativeDay } from "./date-helpers";

/**
 * The 8 real SKAFF ACADEMY programs, in their canonical presentation order (see
 * `displayOrder`). Do not add, remove, or rename programs here without an explicit source of
 * truth — this list previously carried several placeholder/fake programs that have been removed.
 */
export const programs: Program[] = [
  {
    id: "prog-video-production",
    slug: "video-production",
    code: "VID",
    name: "Video Production",
    category: "creative_production",
    displayOrder: 1,
    description: "Learn the full video production process, from planning to filming and editing.",
    overview:
      "A hands-on program covering pre-production planning, camera work, lighting, and editing, using real projects to build a practical production portfolio.",
    whatYouWillLearn: [
      "Plan and storyboard video projects",
      "Operate cameras and lighting for different production settings",
      "Edit footage using industry-standard editing software",
      "Deliver finished video projects from concept to final cut",
    ],
    learningModes: ["physical", "offsite"],
    featured: true,
    isActive: true,
  },
  {
    id: "prog-audio-production",
    slug: "audio-production",
    code: "AUDIO",
    name: "Audio Production",
    category: "creative_production",
    displayOrder: 2,
    description: "Learn studio audio recording, editing, and mixing fundamentals.",
    overview:
      "A hands-on program covering the audio production workflow: recording, editing, mixing, and preparing final audio for release, using a working studio environment.",
    whatYouWillLearn: [
      "Set up and operate studio recording equipment",
      "Edit and clean up recorded audio",
      "Apply basic mixing techniques",
      "Prepare and export finished audio projects",
    ],
    learningModes: ["physical"],
    isActive: true,
  },
  {
    id: "prog-fullstack",
    slug: "full-stack-development",
    code: "FSD",
    name: "Full-Stack Development",
    category: "technology",
    displayOrder: 3,
    description:
      "Build complete web applications, from front-end interfaces to back-end services and databases.",
    overview:
      "This program takes you through the full web development lifecycle, from building user interfaces to designing back-end services, working with databases, and deploying applications. You'll work on practical projects that mirror real industry workflows.",
    whatYouWillLearn: [
      "Build responsive user interfaces with modern front-end frameworks",
      "Design and build back-end services and APIs",
      "Work with relational databases and data modeling",
      "Use version control and collaborative development workflows",
      "Deploy and maintain web applications",
    ],
    learningModes: ["physical", "online"],
    featured: true,
    isActive: true,
  },
  {
    id: "prog-backend",
    slug: "backend-development",
    code: "BE",
    name: "Backend Development",
    category: "technology",
    displayOrder: 4,
    description: "Design and build the server-side systems that power web and mobile applications.",
    overview:
      "This program covers server-side programming, API design, database management, and the fundamentals of building reliable back-end systems for real applications.",
    whatYouWillLearn: [
      "Design and build RESTful APIs",
      "Work with databases and data modeling",
      "Apply authentication and authorization fundamentals",
      "Structure and organize server-side applications",
    ],
    learningModes: ["physical", "online"],
    isActive: true,
  },
  {
    id: "prog-frontend",
    slug: "frontend-development",
    code: "FE",
    name: "Frontend Development",
    category: "technology",
    displayOrder: 5,
    description: "Focus on building fast, accessible, and well-structured user interfaces for the web.",
    overview:
      "A focused track on front-end engineering: structuring interfaces, working with modern JavaScript frameworks, and building interfaces that are responsive, accessible, and maintainable.",
    whatYouWillLearn: [
      "Structure web pages with semantic HTML and modern CSS",
      "Build interactive interfaces with JavaScript and a modern framework",
      "Apply responsive and accessible design practices",
      "Work with APIs to render dynamic data",
    ],
    learningModes: ["physical", "online"],
    isActive: true,
  },
  {
    id: "prog-uiux",
    slug: "ui-ux-design",
    code: "UIUX",
    name: "UI/UX Design",
    category: "technology",
    displayOrder: 6,
    description: "Research, design, and test digital products that are usable and intuitive.",
    overview:
      "A practical design program covering the end-to-end product design process: user research, wireframing, prototyping, and usability testing, using industry-standard design tools.",
    whatYouWillLearn: [
      "Conduct basic user research and translate it into design decisions",
      "Create wireframes and interactive prototypes",
      "Apply visual design and design systems thinking",
      "Test and iterate on designs based on user feedback",
    ],
    learningModes: ["physical", "online"],
    isActive: true,
  },
  {
    id: "prog-ai",
    slug: "power-of-ai",
    code: "AI",
    name: "Power of AI",
    category: "technology",
    displayOrder: 7,
    description: "An introduction to practical AI tools and workflows for real-world use.",
    overview:
      "This program introduces the fundamentals of artificial intelligence, with an emphasis on practical, applied use of AI tools rather than pure theory.",
    whatYouWillLearn: [
      "Understand core AI and machine learning concepts",
      "Work with data preparation and model training basics",
      "Apply pre-built AI tools and APIs to real problems",
      "Explore responsible, practical use of AI in projects",
    ],
    learningModes: ["physical", "online"],
    isActive: true,
  },
  {
    id: "prog-digital-marketing",
    slug: "digital-marketing-social-media",
    code: "DMSM",
    name: "Digital Marketing & Social Media Management",
    category: "digital_business",
    displayOrder: 8,
    description: "Plan, run, and measure marketing campaigns across digital and social channels.",
    overview:
      "A practical program covering digital marketing strategy, content planning, and social media management, aimed at preparing learners to manage real online marketing campaigns.",
    whatYouWillLearn: [
      "Plan content and campaigns across social media platforms",
      "Apply core digital marketing and advertising concepts",
      "Use analytics to measure and adjust campaign performance",
      "Manage a brand's online presence and community",
    ],
    learningModes: ["physical", "online", "offsite"],
    featured: true,
    isActive: true,
  },
];

// Internal admin/student architecture data — not shown on public pages.
export const intakes: Intake[] = [
  {
    id: "intake-1",
    programId: "prog-fullstack",
    label: "Cohort A",
    status: "active",
    applicationsOpen: false,
    applicationOpensAt: relativeDay(-230),
    applicationClosesAt: relativeDay(-215),
    startDate: relativeDay(-200),
    endDate: relativeDay(160),
    studyModes: ["physical", "online"],
    capacity: 25,
  },
  {
    id: "intake-2",
    programId: "prog-uiux",
    label: "Cohort B",
    status: "upcoming",
    applicationsOpen: true,
    applicationOpensAt: relativeDay(-30),
    applicationClosesAt: relativeDay(10),
    startDate: relativeDay(20),
    endDate: relativeDay(180),
    studyModes: ["physical", "online"],
    capacity: 20,
  },
  {
    id: "intake-3",
    programId: "prog-video-production",
    label: "Cohort A",
    status: "upcoming",
    applicationsOpen: true,
    applicationOpensAt: relativeDay(-20),
    applicationClosesAt: relativeDay(15),
    startDate: relativeDay(30),
    endDate: relativeDay(200),
    studyModes: ["physical", "offsite"],
    capacity: 20,
  },
  {
    id: "intake-4",
    programId: "prog-audio-production",
    label: "Cohort A",
    status: "upcoming",
    applicationsOpen: true,
    applicationOpensAt: relativeDay(-10),
    applicationClosesAt: relativeDay(20),
    startDate: relativeDay(45),
    endDate: relativeDay(210),
    studyModes: ["physical"],
    capacity: 15,
  },
  {
    id: "intake-5",
    programId: "prog-backend",
    label: "Cohort A",
    status: "completed",
    applicationsOpen: false,
    applicationOpensAt: relativeDay(-320),
    applicationClosesAt: relativeDay(-305),
    startDate: relativeDay(-300),
    endDate: relativeDay(-60),
    studyModes: ["physical", "online"],
    capacity: 20,
  },
  {
    id: "intake-6",
    programId: "prog-frontend",
    label: "Cohort A",
    status: "upcoming",
    applicationsOpen: true,
    applicationOpensAt: relativeDay(-5),
    applicationClosesAt: relativeDay(25),
    startDate: relativeDay(40),
    endDate: relativeDay(220),
    studyModes: ["physical", "online"],
    capacity: 20,
  },
  {
    id: "intake-7",
    programId: "prog-ai",
    label: "Cohort A",
    status: "cancelled",
    applicationsOpen: false,
    applicationOpensAt: relativeDay(-60),
    applicationClosesAt: relativeDay(-20),
    startDate: relativeDay(0),
    endDate: relativeDay(150),
    studyModes: ["physical", "online"],
    capacity: 20,
  },
  {
    id: "intake-8",
    programId: "prog-digital-marketing",
    label: "Cohort A",
    status: "active",
    applicationsOpen: false,
    applicationOpensAt: relativeDay(-250),
    applicationClosesAt: relativeDay(-235),
    startDate: relativeDay(-220),
    endDate: relativeDay(-40),
    studyModes: ["physical", "online", "offsite"],
    capacity: 25,
  },
  {
    id: "intake-9",
    programId: "prog-digital-marketing",
    label: "Cohort B",
    status: "upcoming",
    applicationsOpen: true,
    applicationOpensAt: relativeDay(-15),
    applicationClosesAt: relativeDay(30),
    startDate: relativeDay(50),
    endDate: relativeDay(230),
    studyModes: ["physical", "online", "offsite"],
    capacity: 25,
  },
];

export const classGroups: ClassGroup[] = [
  {
    id: "class-1",
    intakeId: "intake-1",
    name: "FSD-2026-A",
    capacity: 25,
    status: "active",
    homeRoom: "Lab 3",
    staffLeadId: "staff-1",
  },
  {
    id: "class-2",
    intakeId: "intake-2",
    name: "UIUX-2026-A",
    capacity: 20,
    status: "upcoming",
    homeRoom: "Studio 1",
  },
];
