import type { User, StudentProfile } from "@/lib/types";

export const studentUsers: User[] = [
  {
    id: "user-1",
    accountType: "STUDENT",
    fullName: "Aline Uwimana",
    email: "aline.uwimana@example.com",
    phone: "+250 788 000 111",
    createdAt: "2025-11-02",
    updatedAt: "2025-11-02",
  },
  {
    id: "user-2",
    accountType: "STUDENT",
    fullName: "Eric Niyonshuti",
    email: "eric.niyonshuti@example.com",
    phone: "+250 788 000 222",
    createdAt: "2025-11-05",
    updatedAt: "2025-11-05",
  },
  {
    id: "user-3",
    accountType: "STUDENT",
    fullName: "Diane Mukamana",
    email: "diane.mukamana@example.com",
    phone: "+250 788 000 333",
    createdAt: "2025-11-08",
    updatedAt: "2025-11-08",
  },
  {
    id: "user-4",
    accountType: "STUDENT",
    fullName: "Olivier Ndayisenga",
    email: "olivier.ndayisenga@example.com",
    phone: "+250 788 000 444",
    createdAt: "2025-11-10",
    updatedAt: "2025-11-10",
  },
];

export const studentProfiles: StudentProfile[] = [
  {
    id: "student-1",
    userId: "user-1",
    studentNumber: "SKF-2026-0001",
    status: "active",
    programId: "prog-fullstack",
    intakeId: "intake-1",
    classGroupId: "class-1",
    dateOfBirth: "2001-04-12",
    nationality: "Rwandan",
    nationalId: "1199880012345678",
    address: "Kicukiro, Kigali",
    emergencyContactName: "Jeanne Uwimana",
    emergencyContactPhone: "+250 788 555 111",
    enrolledAt: "2026-02-02",
  },
  {
    id: "student-2",
    userId: "user-2",
    studentNumber: "SKF-2026-0002",
    status: "pending_payment",
    programId: "prog-uiux",
    intakeId: "intake-2",
    classGroupId: "class-2",
    dateOfBirth: "2000-09-18",
    nationality: "Rwandan",
    enrolledAt: "2026-03-02",
    statusMessage:
      "Your account has a pending payment status. Some academic services may be limited until your payment is updated.",
  },
  {
    id: "student-3",
    userId: "user-3",
    studentNumber: "SKF-2026-0003",
    status: "on_hold",
    programId: "prog-fullstack",
    intakeId: "intake-1",
    classGroupId: "class-1",
    dateOfBirth: "1999-02-25",
    nationality: "Rwandan",
    enrolledAt: "2026-02-02",
    statusMessage:
      "Your account is on hold pending confirmation of your updated academic documents. Please contact the Academy office.",
    internalNotes: "Awaiting updated national ID copy — flagged by registrar on document review.",
  },
  {
    id: "student-4",
    userId: "user-4",
    studentNumber: "SKF-2026-0004",
    status: "suspended",
    programId: "prog-fullstack",
    intakeId: "intake-1",
    classGroupId: "class-1",
    dateOfBirth: "2000-07-03",
    nationality: "Rwandan",
    enrolledAt: "2026-02-02",
    statusMessage: "Your account is currently suspended. Please contact SKAFF Academy administration for resolution.",
    internalNotes: "Suspended after repeated missed payments beyond the grace period. Review before reinstating.",
  },
];
