import type { StudentStatusHistoryEntry } from "@/lib/types";
import { relativeDay } from "./date-helpers";

export const studentStatusHistory: StudentStatusHistoryEntry[] = [
  {
    id: "sh-1",
    studentId: "student-1",
    timestamp: "2026-02-02T09:00:00.000Z",
    actor: "system",
    actorName: "System",
    previousStatus: "applicant",
    newStatus: "active",
    publicMessage: "Welcome to SKAFF ACADEMY — your enrollment is confirmed.",
  },
  {
    id: "sh-2",
    studentId: "student-2",
    timestamp: "2026-03-02T09:00:00.000Z",
    actor: "system",
    actorName: "System",
    previousStatus: "applicant",
    newStatus: "pending_payment",
    publicMessage: "Your enrollment is confirmed pending your first tuition payment.",
  },
  {
    id: "sh-3",
    studentId: "student-3",
    timestamp: "2026-02-02T09:00:00.000Z",
    actor: "system",
    actorName: "System",
    previousStatus: "applicant",
    newStatus: "active",
  },
  {
    id: "sh-4",
    studentId: "student-3",
    timestamp: relativeDay(-5, 11),
    actor: "admin_staff",
    actorName: "Academic Office",
    previousStatus: "active",
    newStatus: "on_hold",
    publicMessage:
      "Your account is on hold pending confirmation of your updated academic documents. Please contact the Academy office.",
    internalNote: "Awaiting updated national ID copy — flagged by registrar on document review.",
  },
  {
    id: "sh-5",
    studentId: "student-4",
    timestamp: "2026-02-02T09:00:00.000Z",
    actor: "system",
    actorName: "System",
    previousStatus: "applicant",
    newStatus: "active",
  },
  {
    id: "sh-6",
    studentId: "student-4",
    timestamp: relativeDay(-30, 14),
    actor: "admin_staff",
    actorName: "Academic Office",
    previousStatus: "active",
    newStatus: "on_hold",
    publicMessage: "Your account has been placed on hold due to an overdue tuition balance.",
    internalNote: "First notice sent regarding overdue balance.",
  },
  {
    id: "sh-7",
    studentId: "student-4",
    timestamp: relativeDay(-14, 10),
    actor: "admin_staff",
    actorName: "Academic Office",
    previousStatus: "on_hold",
    newStatus: "suspended",
    publicMessage: "Your account is currently suspended. Please contact SKAFF Academy administration for resolution.",
    internalNote: "Suspended after repeated missed payments beyond the grace period. Review before reinstating.",
  },
];
